About me section and recent works section completed
admirerbrown/portfolio pull request #2
Opened 2022-10-28 18:53 UTC by admirerbrown

i completed all project requirements on my portfolio project. I performed the following tasks:
-built the full html sections for the project
-built the style-sheet for the project
-fixed all linter errors and cleaned the project
-ensured finish code output looks almost like the figma template.

2022-10-28 20:01 UTC, mckent05 requested changes
Hi @admirerbrown,

# STATUS: CHANGES REQUIRED ♻️ ♻️  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/198721774-e539f4e3-b6c2-4686-8551-c10a862833cb.gif)

## Highlights
- All linter checks are passing correctly ✔️ ✔️ 
- Your portfolio looks good 👍 👍 
- GitHub flow was used correctly 👏 

## Required Changes ♻️
- Your portfolio currently doesn't fit well into all mobile screen sizes i.e it is not responsive across screen sizes `<768px`. I advise that you try to make your portfolio responsive. Please fix this 👍 👍 
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 20:01 UTC, mckent05 commented on style.css
> +}
- According to the project requirements, the content of each of your project cards should be aligned with flexbox. Please try to fix this 👍 👍

2022-10-28 20:01 UTC, mckent05 commented on index.html
> +          <a class="view"><button class="btn" type="button">See Project</button></a>
- To help improve the HTML structure of your page, I suggest you wrap this in either an `a` tag or `button` tag and not both. Please fix this for all project buttons as they might apply 🙏

2022-10-28 20:01 UTC, mckent05 commented on index.html
> +      </ul>
- To help improve your page's HTML structure, I suggest you do not need to use a `ul` tag to wrap the content here. Please remove the `ul` tag and corresponding `li` tags 🙏

2022-10-28 20:01 UTC, mckent05 commented on index.html
> +            </button></a>
- Just as I suggested earlier, please use either an `a` tag or `button` tag, not both. Please fix this 👍 👍

2022-10-28 20:01 UTC, mckent05 commented on index.html
> +  </section>
- To help improve your HTML structure and ensure your page is readable and maintainable. I suggest you include this section in your `about me` section (the section above). Also, you can consider wrapping this section in a `ul` tag and then wrap individual language, frameworks and skills in a `li` tag. Please fix this 👍 👍

2022-10-28 20:01 UTC, mckent05 commented on index.html
> +  </section>
- This section of the page is not meant for this milestone, I advise that you remove this section and include it when you get to the required milestone. Please fix this 🙏 🙏

2022-10-28 23:17 UTC, tufoinnkuo10 requested changes
Hi @admirerbrown 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/xNJPkAQnLGVGjYpsBW/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-28 23:17 UTC, tufoinnkuo10 commented on index.html
> +        <a>
- [optional] the about me is a heading and does not need the `a tag `

2022-10-28 23:17 UTC, tufoinnkuo10 commented on index.html
> +    <section id="abt-me-items">
- [ ] like the previous reviewer noted, the about me items should be inside the about me `section tag` not on their own personal section tag. They all make up the skills and framework about you and should be together. please fix that.

2022-10-29 00:58 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @admirerbrown , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights :heavy_check_mark: 
- [ ] All linter checks are passing :white_check_mark: 
- [ ] Implemented all the changes from the previous reviewer :white_check_mark: 

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 05:00 UTC, merged